version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    image: docker/laravelproject
    container_name: app
    tty : true
    restart: unless-stopped
    environment:
      DB_HOST : db
      DB_PASSWORD : password
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile : ./docker/nginx/Dockerfile
      args:
        - NGINXUSER=${NGINXUSER:-www-data}
        - NGINXGROUP=${NGINXGROUP:-www-data}
    image: docker/nginx
    container_name: webserver
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes: 
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on: 
      - app

  db:
    image: mysql:5.7.22
    container_name : db
    environment : 
      MYSQL_DATABASE : laravel
      MYSQL_ROOT_PASSWORD : password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local